### ISSUE TITLE
Empty box in builder

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Forms-Extension#10]
I have the latest git version of Unyson and extensions.

The form builder has an [empty box](http://static.md/71fe78e81fc255991cb6ff5804da8832.png), when I click on it in console I get an error from [builder.js:190](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/f79ffba0163cd321d51cbf34214b860dc6ea8413/includes/option-types/builder/static/js/builder.js#L190)

``` javascript
Uncaught TypeError: Cannot read property '$el' of null
```

The box html is

```
<div class="..." data-builder-item-type="form-header-title"></div>
```

**Comment by GheorgheP** [comment]
Please make sure you have the latest development version of the [Builder Extension](https://github.com/ThemeFuse/Unyson-Builder-Extension) too.

**Comment by ghost** [comment]
I deleted all extensions then [cloned them all](https://gist.github.com/moldcraft/dceae5f6081f72cc1153) and the blank square is no longer there.
