### ISSUE TITLE
Creek characters are not recognized

### ISSUE THREAD

**Issue by xperter** [ThemeFuse/Unyson-Forms-Extension#15]
The contact form works well at the English version. I mean that if somebody puts greek characters at fields Name & Surname, these characters are not recognized at the e-mail that my client receives. 

Is it any escape issue ?

Thanks

**Comment by xperter** [comment]
we have update  all the extension from admin panel.

but still receive same issue. http://puu.sh/k6KBx/c7f477d940.png

Should i update this extension manually ?

Thanks

**Comment by ghost** [comment]
We haven't release the fix yet https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/139

I will release it now but it will be available from admin panel after one hour
