### ISSUE TITLE
Pre-send/mail hook?

### ISSUE THREAD

**Issue by rawcreative** [ThemeFuse/Unyson-Forms-Extension#16]
Is it currently possible to hook into process_form method (or override it) to perform additional tasks prior to the form data being passed to the mailer? Or could an action/hook be added so this is possible?

Use Case: We currently have a client who has requested to have form submissions logged due to previous solutions being unreliable. We were simply going to create an 'entries' post type which would be created/populated with the submission data, but there doesn't seem to be a way to hook into that process in any way.

**Comment by fhqvst** [comment]
I've been wanting to do the exact same thing, but didn't find any good documentation on it.
As far as I can tell, the contact form extension only exposes one hookable action: `fw_ext_forms_frontend_submit`. If we hook into it we can extract the submitted values from `$_POST`, and then pair the unique field ID's to the right fields by using `fw_ext_contact_forms_get_option($form['id'])` inside the hooked function.

**Comment by rawcreative** [comment]
Yes that hook can be used but it doesn't provide any useful data other than the form id. This means that all the form data has to be re-extracted just like it's done in the method calling that action. Plus since the extract_shortcode_item method is private it wouldn't be able to be used to parse the data, so that also has to be rewritten. Currently the only way to actually achieve what we're trying to do is to rewrite code that already exists and is running, or to implement a custom mailer which handles the logging/post creation but itself is quite hacky as a mailer shouldn't be handling those type of tasks, but unfortunately it's the only place where the submission data can be accessed.

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/c686546db128483e92c4e33379ffd11a0fc09cbf/class-fw-extension-forms.php#L227
