### ISSUE TITLE
Is there a way to create a telephone input with validation using the existing builder item types

### ISSUE THREAD

**Issue by jsrothwell** [ThemeFuse/Unyson-Forms-Extension#18]
Hi, 

I am building a site using Unyson for my employer. So far it has far exceeded what I intended it for.

I have been asked to create a form that includes input for a phone number. I have tried using the number type but Im not getting the results I want.

Is there something that I am missing or do I need to create a custom item type for Phone numbers.

Any help would be great. We need a Unyson tips site!

**Comment by llemurya** [comment]
@jsrothwell you can create your [Form Builder Item type](http://manual.unyson.io/en/latest/extension/forms/index.html#create-form-builder-item-type) or use the existing number item type
