### ISSUE TITLE
Browser side validation

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Forms-Extension#2]
Is there planned CSS/JS front end validation for the text fields?

Link: http://themeforest.net/forums/thread/meet-unyson-the-free-drag-drop-wordpress-framework/141818?page=12#1199918

**Comment by ghost** [comment]
Some users have [overwritten](https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/457601d75cc68a9763e3e6ce2e005fe6a231fcf1/includes/option-types/form-builder/items/checkboxes/class-fw-option-type-form-builder-item-checkboxes.php#L231) the form item views to make some customizations, so if we will implement this feature the default views will have frontend validation but the overwritten one will not.
