### ISSUE TITLE
Keeps prompting to update the Breadcrumbs extension

### ISSUE THREAD

**Issue by jsrothwell** [ThemeFuse/Unyson-Forms-Extension#20]
Since the most recent update Unyson keeps prompting me to update the Breadcrumbs extension. After updating, Unyson reverts and notifies me I need to update extensions. Breadcrumbs yet again

**Comment by ghost** [comment]
Sorry, [fixed](https://github.com/ThemeFuse/Unyson-Breadcrumbs-Extension/commit/d969be5b92932142235cf471c55024d1790ba75a) (If forgot to update the version in manifest). Update it again.
