### ISSUE TITLE
Mail not receive in hotmail

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson-Forms-Extension#21]
Today one of my client complain they dont receive mail in hotmail. 
I have also check from our server and another server i am not receive mail in hotmail. but gamil, yahoo, and others work fine.

This is really confusing issue :/

Is there any solution for this ?

Thanks

**Comment by ghost** [comment]
I think hotmail has more strict anti-spam rules, and the emails your server is sending are not passing those rules.

Try to send emails via another plugins or directly from php, if the behavior will be the same then it's a server email/dns configuration issue instead of Forms issue.

**Comment by Ataurr** [comment]
I have send mail from a php script which received mail without any issue.

**Comment by ghost** [comment]
I don't have time to inspect this issue.

Please inspect it yourself by sending emails from php script using [this function](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/master/helpers.php#L3) and try to find [which parameter](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/ed7e6aeccb9d04756662e61850d807616486abc1/includes/send-methods/class-fw-ext-mailer-send-method-smtp.php#L149-L150) causes hotmail to reject the email.
