### ISSUE TITLE
Contact form fails to send message

### ISSUE THREAD

**Issue by dimichatzi** [ThemeFuse/Unyson-Forms-Extension#26]
![screenshot](https://cloud.githubusercontent.com/assets/16350057/13438050/edd768e8-dfef-11e5-9479-36621167227b.jpg)
Ηi,

While trying to send two test messages on my client’s contact form, both of them fail to be sent and i get the failure message “Failed to send your message. Please try again later.” Why does this happen?

Please check my attached screenshot. I use your Unison extension.
The website URL is http://manos-rentacar.com/

Thanx in advance.

**Comment by ghost** [comment]
Hello,

I did a search in the entire WordPress (all plugins and themes) and I can't find the "Failed to send your message" text.

Please do a search in all files in your theme, maybe the problem is there.

Also which send method are you using? (It is configured in Mailer settings)

**Comment by dimichatzi** [comment]
Hi,

I use SMTP send method. Please check my attached screenshots.

![screenshot-1](https://cloud.githubusercontent.com/assets/16350057/13454304/d67e6f1a-e05e-11e5-9445-801481132abd.jpg)
![screenshot-2](https://cloud.githubusercontent.com/assets/16350057/13454306/db5338ea-e05e-11e5-8d26-78d1f286072b.jpg)

The message i get is the failure message at settings-->options of contact form.

**Comment by ghost** [comment]
Please uncomment [this line](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/v1.2.3/includes/send-methods/class-fw-ext-mailer-send-method-smtp.php#L163) and try to send a message, it should display a lot of debug messages/errors and it will help understand the problem
