### ISSUE TITLE
Is it possible to use grid form. ?

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson-Forms-Extension#28]
As my form style in left side 3 and right side one ( Textarea only )
I have tried to set like this but cant. 
![screenshot 2016-03-13 06 05 54](https://cloud.githubusercontent.com/assets/6223399/13728544/7e2e9416-e946-11e5-9edc-ff9836251125.png)

I have used last time caldera form. which have grid system. but now my next theme i dont want to use any third party form for this kind of style.

Can you please provide us details if it can be possible with forms extensions. Its really help me lot if its possible with this extension.

Thanks much

**Comment by ghost** [comment]
Sorry, It's not possible https://github.com/ThemeFuse/Unyson/issues/832
