### ISSUE TITLE
Mail not sent on godady server

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Forms-Extension#36]
I have a problem on a godady server to send a email via contat form, I try gmail account, but didn't work

**Comment by moldcraft** [comment]
Please uncomment [this line](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/v1.2.5/includes/send-methods/class-fw-ext-mailer-send-method-smtp.php#L173) and try to send an email. It should output on page debug information.

**Comment by ghost** [comment]
You can add test in some php file [the `wp_mail()` function](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/v1.2.5/includes/send-methods/class-fw-ext-mailer-send-method-wpmail.php#L60)

**Comment by andronic90** [comment]
Thanks, I will test, and say the resultat

**Comment by andronic90** [comment]
The result of:
`$result = wp_mail(
    $email->get_to(),
    $email->get_subject(),
    $email->get_body()
);`

return true. but the email didn't receive on email.

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-Mailer-Extension/compare/ee83582de3a74dae044f8ce6f225e39fbf5881b1...d1c30e461a15451250e6cf29207fbd0bc122cf6f
