### ISSUE TITLE
Extension/Shortcode disable

### ISSUE THREAD

**Issue by nextgeni-santosh** [ThemeFuse/Unyson-Forms-Extension#37]
Hi, 
   Is there any way to disable extension shortcode/section for some time from wordpress admin panel. Unyson support only remove and reset the extension shortcode. It is posible to make enable and disable option for every shorcode?? please help.

Regards,
Santosh

**Comment by ghost** [comment]
> disable extension shortcode/section for some time

So you want to set a timer when the shortcodes extension must be disabled and then activated back?

> It is posible to make enable and disable option for every shorcode??

[Yes](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#disabling-shortcodes)

**Comment by nextgeni-santosh** [comment]
This is not a solution which I want. I want enable and disable button in wordpress admin in every section. I have my home page with 5 sections, suppose I want to show only 3 sections. and other 2 I want to disable.

**Comment by ghost** [comment]
You can add a custom option (switch) for section shortcode and display nothing in `view.php` if that option is set

http://manual.unyson.io/en/latest/extension/shortcodes/index.html#overwriting-shortcodes

**Comment by nextgeni-santosh** [comment]
Thanks alot. It worked for me.
