### ISSUE TITLE
Custom Shortcode issue

### ISSUE THREAD

**Issue by nextgeni-santosh** [ThemeFuse/Unyson-Forms-Extension#38]
Hi,

I have an issue in custom shortcode. I made my custom links shorcode for my site home page. and I have also using same link in my work page. First I create links for home page. now I want to repeats  same links in work page. but problem is that on work page I should make links section again. is there any solution i make one time for home page. then it can b use in other pages also when needed.

Regards,
Santosh

**Comment by ghost** [comment]
Hello,

The only solution at the moment is to put the desired shortcode in a section or column, [save it as a template](https://static.md/3043109bc3689b6cdd707846cd846317.png) then in another page [load it from templates](https://static.md/49f8bb517fe4fa809a2d08dab6fb7d83.png)

**Comment by nextgeni-santosh** [comment]
my section or column does not work. there is only one option to save whole page. but I want to reuse my section. how can I add section in template??

**Comment by ghost** [comment]
https://vid.me/6yST

**Comment by nextgeni-santosh** [comment]
I understand the video tuterial, but save as template icon do not show in my any section. what can I do now?

**Comment by nextgeni-santosh** [comment]
there is only 3 option in my section edit, duplicate and remove. how can I get fourth option which I seen in ur video tutorial. please help.

**Comment by ghost** [comment]
Which Unyson version do you have installed? Are extensions up-to-date?

**Comment by nextgeni-santosh** [comment]
I am using Version: 2.5.0.

**Comment by nextgeni-santosh** [comment]
After update plugin this error occurs, "Fatal error: Call to undefined function wp_add_inline_script() in D:\xampp\htdocs\vdweb\wp-content\plugins\unyson\framework\core\components\backend.php on line 457"

**Comment by ghost** [comment]
Very strange, [`wp_add_inline_script()`](https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/functions.wp-scripts.php#L106) is defined in the same file with [`wp_register_script()`](https://github.com/WordPress/WordPress/blob/4.5.3/wp-includes/functions.wp-scripts.php#L139) and they are both used [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.8/framework/core/components/backend.php#L450-L460) but you get error only from the second.

Which WP version do you have installed?

**Comment by nextgeni-santosh** [comment]
Resolved myself. Thanks alot. I appriciate your support.

**Comment by ghost** [comment]
I found the problem, `wp_add_inline_script()` was added in WP 4.5.0

**Comment by nextgeni-santosh** [comment]
Hi, shortcode template, section, column reuse facilty gives us backup of particilar template/section, I want to make that type facility, once I create backup of section and I use that section in others multiple pages. when I change something in origional section, it would also apply automatically every pages section, Is it possible??

**Comment by ghost** [comment]
Hello @santoshnextgeni it is not possible
