### ISSUE TITLE
A couple of things

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson-Forms-Extension#4]
These are a couple of things I've noticed:
1. http://joxi.ru/LmGpqOgcwZDk2l
2. http://joxi.ru/V2VvR06UdGq62v
3. http://joxi.ru/1A5JQELUDwZDrE
4. http://joxi.ru/52aeNWXHE0WY20
5. http://joxi.ru/L21Jpg5URDWMAX
6. Single Line Text -  http://joxi.ru/82Q4pJjTw4RKmd
7. Paragraph Text - http://joxi.ru/52aeNWXHE0vY20
8. Number - http://joxi.ru/12Mx7ygCl8LemJ
9. Multiple Choice - http://joxi.ru/v29ydbRiZj9Z2G, http://joxi.ru/VrweWGyH7gbo2X
10. Single Choice - http://joxi.ru/82Q4pJjTw46Kmd
11. Dropdown - http://joxi.ru/5mdnNK1U3JPVA1
12. Email - http://joxi.ru/52aeNWXHE0BY20
13. Website - http://joxi.ru/8238nGWc9wMkAO
14. Hovers ca la visual builder - http://joxi.ru/KAxMd0phZwYOr8
15. Title and Subtitle - http://joxi.ru/l2ZYnzKCzVOJmJ
16. Options - http://joxi.ru/EA4bn0dco0G7mb
17. Mailer - http://joxi.ru/5mdnNK1U3J5vA1
18. Mailer - http://joxi.ru/8AnN51aizKV0AO

**Comment by GheorgheP** [comment]
1. Short select, the select input is too short: http://screencast.com/t/jEagiiFpj
   - https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/4a4f2e6d357efd9190b657bf7135012cedd919f9
   - https://github.com/ThemeFuse/Unyson-Mailer-Extension/commit/cade7c30276087dc27ac2ac3db97c28273e397d1

**Comment by DimiBaitanciuc** [comment]
I've forgot something here, we have some separators missing on the Settings tab:
1. http://joxi.ru/GrqBd8li46OLmz
2. http://joxi.ru/BA0bnqQcM4zLmy

**Comment by ghost** [comment]
I removed them intentionally to group options.
Ok, we will add them.
