### ISSUE TITLE
Mail not work Forbidden.

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson-Forms-Extension#40]
Hello 
I just tried to send installation site and getting forbiden. 

![hell](https://puu.sh/rDQoN/a93343dc83.png)

I have tried smtp as well. smtp also not working.

Thanks

**Comment by ghost** [comment]
It happens [here](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/bcd08d2765b96edec47e523a32542c3f87b734b0/includes/option-type-mailer/class-fw-option-type-mailer.php#L188-L189). Which role has your user?

**Comment by ghost** [comment]
Please [download latest dev Mailer extension](https://github.com/ThemeFuse/Unyson-Mailer-Extension), extract in `unyson/framework/extensions/mailer` and test.

**Comment by Ataurr** [comment]
Now i am receiving this error.

![hello](https://puu.sh/rDZwx/a59afaa03c.png)

They are using WPMU.

**Comment by Ataurr** [comment]
Strange issue :/
With wpMail test mail working. but  contact form not send any email to email address.

**Comment by ghost** [comment]
Now I am inspecting a client with the same issue. I will come back with a reply later

**Comment by ghost** [comment]
@Ataurr Try to change in Mailer settings the Subject field from "New message" to something else, for example "Contact Form"

**Comment by Ataurr** [comment]
Yes its work fine with wpMail but smtp still not working.

Thanks

**Comment by ghost** [comment]
Uncomment [this line](https://github.com/ThemeFuse/Unyson-Mailer-Extension/blob/980eb2f84b00455206f82369802ac81e1297c496/includes/send-methods/class-fw-ext-mailer-send-method-smtp.php#L178) to debug smtp

**Comment by Ataurr** [comment]
Test email showing this error.

![error](https://puu.sh/rE8pf/6ad4836764.png)

And form showing same error in console.

![error 2](https://puu.sh/rE8vQ/d053fe3089.png)

**Comment by ghost** [comment]
Inspect ajax server response (in Network tab)
