### ISSUE TITLE
Input type=tel

### ISSUE THREAD

**Issue by Konrud** [ThemeFuse/Unyson-Forms-Extension#43]
How can I add new input type=tel (which is crucial now, especially for mobile users) ?

**Comment by GheorgheP** [comment]
You can copy the text [input type](https://github.com/ThemeFuse/Unyson-Forms-Extension/tree/master/includes/option-types/form-builder/items/text) and change the class name,options and view to your needs.

**Comment by Konrud** [comment]
I've tried to do this.
 I've copied all the files into themes/{my-theme}-child/framework-customizations/extensions/forms/includes/builder-items/telephone-type/
But it doesn't work, it actually had ruined some options in Wordpress when I went back.
 It gives me some error about hooks.php
I've tried to implement as it's been written in this article:
http://manual.unyson.io/en/latest/extension/forms/index.html#contents

But unfortunately, it doesn't work at all.
