### ISSUE TITLE
Unyson Contact Form Won't fill in Safari

### ISSUE THREAD

**Issue by kategolden1** [ThemeFuse/Unyson-Forms-Extension#45]
Hi there,
I am working on a client's website but cannot fill in parts of the contact form, such as name, email, etc - it simply won't let me type. It does, however, work in Chrome. Is there a patch to get this functioning across different browsers? You can view the test site at http://rapid.kast.co.nz

**Comment by ViorelEremia** [comment]
Hi Kate,
sorry for a delayed response
can you share again your site to inspect the problem
