### ISSUE TITLE
Problem with "Test connection"

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Forms-Extension#46]
When I press "send a test email" method wp-mail give me this error in console: https://www.screencast.com/t/TgjIXdpz

Please inspect this problem. Thank you!

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Unyson-Mailer-Extension/commit/93828a57b88d1f05394ae67bf6f74f6eed4d6235

**Comment by andreiglingeanu** [comment]
Oh, that was my bad. The cause of it was the introduction of `.fw-backend-option-descriptor` div, sorry.
