### ISSUE TITLE
Not passing form ID

### ISSUE THREAD

**Issue by hibiscustechno** [ThemeFuse/Unyson-Forms-Extension#47]
When we are opening the form through direct url under wordpress admin (Forms > <example form>) it is not passing the form_id hidden value in the form and submit always getting failed due to that . Please find attached screenshot
![screenshot_3](https://user-images.githubusercontent.com/32548642/31236985-4beee980-aa13-11e7-84c9-0eea60287307.jpg)

**Comment by ViorelEremia** [comment]
I don't understand what "direct url under wordpress admin (Forms > )" - "Forms" is a link in admin ddashboard? and what direct url?

**Comment by hibiscustechno** [comment]
Please find attached screenshot . 
![unyson](https://user-images.githubusercontent.com/32548642/31283427-3806445c-aad3-11e7-8357-13d5504c40e5.jpg)

**Comment by hibiscustechno** [comment]
Please find attached screenshot
![uny](https://user-images.githubusercontent.com/32548642/31283471-5b380ea6-aad3-11e7-88d2-b1f16c5e65cb.jpg)

**Comment by ViorelEremia** [comment]
How you get this? unyson doesn't have custom post type forms. Contact form7 plugin?

**Comment by hibiscustechno** [comment]
It is coming from Unyson forms extensions  (http://manual.unyson.io/en/latest/extension/forms/) , when we install forms extensions it will display the custom post type "Forms"

**Comment by ViorelEremia** [comment]
I'm not on my computer now, but I think you are wrong, extension form add shortcode contact form in builder page.

**Comment by ViorelEremia** [comment]
Disable all plugins except for Unyson and if forms yet exists as custom post type drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com - possibly your server has some special configurations that generate this or is a incompatibility between plugins but by default Unyson doesn't have custom post type forms.
