### ISSUE TITLE
Not possible to drag & drop/edit contact form anymore..

### ISSUE THREAD

**Issue by gaurav517** [ThemeFuse/Unyson-Forms-Extension#53]
with unyson version 2.7.9, its not possible to drag & drop or edit a contact form.. I am able to drag and drop other elements except contact form. 
By the time its fixed, I need to change email address in an existing form (created using unyson page builder) urgently, would it be possible to change it somewhere in database?

**Comment by ViorelEremia** [comment]
Are there any errors in browser console when you try to drag contact form?

**Comment by gaurav517** [comment]
sorry for late reply. It did work other day, probably something to with browser cache. Thanks for closing ticket.
