### ISSUE TITLE
Contact Form Setting Instructions?

### ISSUE THREAD

**Issue by Senyors** [ThemeFuse/Unyson-Forms-Extension#54]
I've purchased and installed a WordPress theme ("Recover") that leverages the Unyson Framework. The theme came with a Contact Us page pre-configured with a contact form. Unfortunately, I can't get the form to work (https://www.statzinspection.biz/contact-us/). 

I don't know where the problem is. Is there an issue with my hosting provider? Did the theme vendor introduce a problem? Is the Unyson extension itself at issue? Is it perhaps some combination of the three?

I searched the Internet for some instructions on how the contact form settings tab should be properly configured (both the "options" and the "mailer") but I couldn't find anything--do some official instructions exist anywhere? Is this the proper venue where I can perhaps receive some support regarding the Unyson forms extension?

**Comment by ViorelEremia** [comment]
Unyson contact form is used by thousands of users and it is working.
To test hosting provider install contact form7 and check it is working.
Some instructions you can find here: http://docs.themefuse.com/the-core/your-theme/contact-form/add-a-new-contact-form-to-a-page-the-core
http://docs.themefuse.com/the-core/your-theme/shortcodes/contact-form-1
By default, Unyson doesn't have ajax submit form that means the theme rewrites the unyson functions, try to contact the theme authors if they find that this is a plugin issue then we solve it.

**Comment by Senyors** [comment]
Thanks for the quick and honest feedback! I'll go ahead and contact the theme vendor and see if they can help.
