### ISSUE TITLE
Empty form is passing validation

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Forms-Extension#7]
When you add a Contact Form in the bulder, don't configure it and save the post, open the page in frontend and click the Submit button, the form is trying to send an email.
I think the form should not pass the validation (and not send emails) if it has no items (is empty), because users testing the framework or forgetting to configure a form, will allow random site visitors to send emails (spam) just by clicking the Submit button.
You can make a validation error: The form is empty, please add at least one item.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/021113b45ce235877db0128d02abd3d0b5554a2c
