### ISSUE TITLE
Ajax Form submit and validation 

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Unyson-Forms-Extension#8]
Hi 
Thanks again. Is there any plan to use ajax in form submission?

**Comment by ghost** [comment]
Hi,
Which form?

**Comment by webangon** [comment]
Hi 
The contact form extension

**Comment by ghost** [comment]
Use [this script](https://github.com/ThemeFuse/Unyson/blob/master/framework/static/js/fw-form-helpers.js) to make forms ajax submittable (it is used for [Theme Settings form ajax submit](https://github.com/ThemeFuse/Unyson/blob/master/framework/views/backend-settings-form.php#L147)). You can copy it in your theme or enqueue with url directly from plugin.

**Comment by webangon** [comment]
I am sorry that did not work for me. As far as I know I have to localize the variables and I have seen that it is done nicely here(http://demo.themefuse.com/exposure/?page_id=258)  The jquery script for the demo site(http://demo.themefuse.com/exposure/wp-content/themes/exposure-parent/js/general.js?ver=1.0)

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson/issues/353#issuecomment-86149401
